language: ruby
dist: xenial
cache: bundler

matrix:
  include:
  - rvm: 2.4
  - rvm: 2.5
  - rvm: 2.6
  - rvm: 2.6
    env: COVERAGE=PartialSummary,Coveralls
  - rvm: 2.7
  - rvm: truffleruby
  - rvm: jruby
  - rvm: ruby-head
  allow_failures:
  - rvm: truffleruby
  - rvm: ruby-head
  - rvm: jruby-head
